### ISSUE TITLE
Error in Angular 13

### ISSUE THREAD

**Issue by suwenjiang** [Esri/calcite-components-examples#115]
Trying to build a sample application with my local environment which is anugalr 13 with typescript 4.4.4. 
However, just founding it's unable to get all the necessary .ts files when using npm install which results 
error when starting the application 

==============
                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: ../node_modules/@esri/calcite-components/dist/types/components.d.ts:28:34 - error TS2307: Cannot find module './components/pagination/pagination' or its corresponding type declarations.

28 import { PaginationDetail } from "./components/pagination/pagination";
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Error: ../node_modules/@esri/calcite-components/dist/types/components.d.ts:29:29 - error TS2307: Cannot find module './components/pick-list/shared-list-logic' or its corresponding type declarations.

29 import { ListFocusId } from "./components/pick-list/shared-list-logic";
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: ../node_modules/@esri/calcite-components/dist/types/components.d.ts:37:53 - error TS2307: Cannot find module './components/tree/interfaces' or its corresponding type declarations.

37 import { TreeSelectDetail, TreeSelectionMode } from "./components/tree/interfaces";

**Comment by benelan** [comment]
Hi @suwenjiang, this issue is fixed in `beta.80`.
