### ISSUE TITLE
Bug:  icons not displaying in version `1.0.0-beta.51`

### ISSUE THREAD

**Issue by alexanderela** [Esri/calcite-components-examples#15]
We are currently implementing the Pagination component from `calcite-components` [using the loader specified in this repo](https://github.com/Esri/calcite-components-examples/tree/master/react#calcite-components-with-react).  

When using `calcite components version 1.0.0-beta.46` the Pagination component works correctly, [as demonstrated in our deployed app](https://test.assistant.aws.esri-ps.com/content?queryScope=USER&num=20&start=1&sortField=modified&sortOrder=desc&folder=allmycontent).

However, after updating to `calcite components version 1.0.0-beta.51`, the calcite components icon assets are not appearing in the Pagination component and we are getting the following console error.  It appears that the icon asset paths are not being read correctly by the icon elements.  Reverting to `calcite components version 1.0.0-beta.46` fixes the issue.

<img width="1175" alt="68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3565653364636432663665303235326139313963653962652f62656538333132652d323266662d343161332d626166392d333135396330323566306232" src="https://user-images.githubusercontent.com/30238776/113345787-2ece2400-92f0-11eb-80ef-fb6923735a8c.png">

![imgpsh_mobile_save-1](https://user-images.githubusercontent.com/30238776/113345808-34c40500-92f0-11eb-94c5-03f174d886e2.jpg)

![62599128-9895-4f3d-a4ff-eb003471b0e1](https://user-images.githubusercontent.com/30238776/113345829-3ab9e600-92f0-11eb-8909-20ac9f3e6f64.jpg)

**Comment by paulcpederson** [comment]
I think we updated these. CC is now on beta.56, @alexanderela are you still experiencing this with the more recent versions?

**Comment by julio8a** [comment]
@alexanderela, Is this still an issue? we are on beta.62
