### ISSUE TITLE
React: CalciteAlert component not displaying close button ("x16" is not a valid calcite-ui-icon name)

### ISSUE THREAD

**Issue by lisastaehli** [Esri/calcite-components-examples#153]
_Please let me know if this is the wrong repo to post this issue - I wasn't able to find a `calcite-components-react` repo._ 🙈 

### Description
We are having an issue with the `CalciteAlert` where the close button is not displayed correctly when `dismissible` is set to `true`.

<img width="500" src="https://user-images.githubusercontent.com/27951811/178434294-0794abd4-00f0-4c88-821e-b5199e4f3cb4.png" />

When looking at the **HTML elements**, the `path` element looks like it has no shape:

<img width="500" src="https://user-images.githubusercontent.com/27951811/178434247-b0b6cf86-52fa-4bea-8f6c-17d8c8955dd8.png" />

And I am also seeing the following **console error**:

<img width="500" src="https://user-images.githubusercontent.com/27951811/178434808-d18b82f2-6df8-4463-97f4-ba61bd9e0435.png" />

On our end, we aren't setting the icon to `"x16"` so I am wondering if any knows what's going on here :)? Thanks for the help!

### Code 

This is how we are currently using `CalciteAlert`:

```javascript
<CalciteAlert
  key={index}
  active
  placement="top"
  autoDismiss={!dismissible}
  autoDismissDuration="slow"
  label="notification-center-alert"
  color={getAlertColor(notificationType)}
  onCalciteAlertClose={() => dispatch({ type: HIDE, index })}
  intlClose={intl.formatMessage(commonMessages.close)}
>
    <div slot="title">
      {notificationType === NotificationType.Danger &&
      intl.formatMessage(messages.error)}
    </div>
    <div slot="message">{intl.formatMessage(message, data)}</div>
</CalciteAlert>
```

### Environment
- OS: Windows 10
- Browser: Chrome (103.0.5060.114)

Versions used:
- `"calcite-ui-icons-react": "^0.38.0"`
- `"@esri/calcite-components-react": "^0.24.0"`
- `"react": "^16.12.0"`

(I also tried it with lower versions & also saw the issue.)

Not sure if this is an issue in `calcite-components`, `calcite-ui-icons` (doesn't look like it from the [example on the website](https://developers.arcgis.com/calcite-design-system/components/alert/)) or something specific to the `calcite-components-react` or `calcite-ui-icons-react` (some incompatibility maybe?).

**Comment by benelan** [comment]
Hi Lisa, thanks for logging the issue. For future reference, `calcite-components-react` issues can be logged in the [`calcite-components` repo](https://github.com/Esri/calcite-components). One thing I noticed in the code snippet is this line:
```js
autoDismiss={!dismissible}
```
should be:
```js
autoDismiss={dismissible ? undefined : true}
```
based on this "gotcha" in the documentation:
https://developers.arcgis.com/calcite-design-system/frameworks/#boolean-attributes

I don't think that's causing this issue, but just a heads up. 

Can you please try reproducing the issue in codesandbox or a github repo so we can investigate? Here is a template to help get started: 
https://codesandbox.io/s/calcite-template-p95kp?file=/src/App.js

I wasn't able to reproduce the issue by importing alert and adding this code to the template:
```jsx
      <CalciteAlert
        key={1}
        active
        placement="top"
        label="notification-center-alert"
      >
        <div slot="title">Test</div>
        <div slot="message">Testing alert issue</div>
      </CalciteAlert>

```
Let me know if you run into any issues or have any questions. Thanks!

**Comment by lisastaehli** [comment]
HI @benelan :) thanks again for your help. At the end the problem was that we did not yet copy some of the assets to the local assets folder as described [here](https://github.com/Esri/calcite-components-examples/tree/master/react#copy-local-assets). Maybe also helpful for you to know that such an error message can be an indication of the local files not being there :)
