### ISSUE TITLE
Need a proper sample with map and layout 

### ISSUE THREAD

**Issue by JackFanZhang** [Esri/calcite-components-examples#175]
Hi, may I suggest enhance the react examples with a sample application layout like how the AGS Web Viewer looks? e.g. with a map, the action buttons etc. thank you.

**Comment by benelan** [comment]
Good idea. I started putting a react/calcite/mapping sample together awhile ago if you need something in the meantime. 

https://github.com/benelan/calcite-samples/tree/master/arcgis-react
https://calcite-arcgis-react.vercel.app/

Although its not using `calcite-action-bar` if that's what you're looking for.

**Comment by JackFanZhang** [comment]
Thank you @benelan, it's a good start.
