### ISSUE TITLE
Issue with Editor Widget in Esri's JavaScript SDK version 4.27 and it's calcite-components dependency in Angular framework

### ISSUE THREAD

**Issue by egonher** [Esri/calcite-components-examples#263]
I'm experiencing unexpected behavior in the Widget Editor of the latest version of the SDK and I suspect it has to do with the widget's dependency on the calcite components. This happens Just with the javascript ANgular framework implementation.

**Actual behavior**
When employing the version 4.27 of Esri's JavaScript SDK, I've noticed that the Editor widget does not update data, though it does allow for deletion. Importantly, this behavior is not replicated when using version 4.26 of the same SDK with an identical codebase.

**Expected behavior**
The Editor widget should allow data updates seamlessly, as observed with the 4.26 SDK version.

**Reproduction sample**
https://github.com/Esri/jsapi-resources/compare/main...egonher:jsapi-resources-widget-editor-4.27-angular-test:calcite-test

**Note**
When I use version 4.26 of the sdk I don't see the problem, but the calcite dependency corresponds to version ~1.0.7

I have verified that the problem starts with version 1.3 of calcite-components when used in combination with version 4.26 of the SDK which does not reproduce the bad behavior without the implicit implementation of Calcite in angular framework.

I have observed that the ^4.27 version of the sdk has a dependency on the calcite-components in the ^1.4.2 version, so I wonder if the problem could be focused on the calcite library which affects the latest version of the sdk.

**Comment by andygup** [comment]
Hi @egonher please don't open issues in multiple places, it causes confusion between teams. We are currently working this issue on [`jsapi-resources`](https://github.com/Esri/jsapi-resources/issues/481) as we try to narrow down the problem.

**Comment by andygup** [comment]
@egonher whoops, yes, actually this was my mistake, but it's okay that this one is closed. Thanks for the additional information, that helps as we are trying to narrow down the issue.
