### ISSUE TITLE
Would you provide a NextJS example?

### ISSUE THREAD

**Issue by mstuart1** [Esri/calcite-components-examples#267]
Is it possible to provide a nextjs example or is there a specific reason to NOT use calcite with NextJS?

**Comment by geospatialem** [comment]
> Is it possible to provide a nextjs example or is there a specific reason to NOT use calcite with NextJS?

Hi @mstuart1 Calcite is [framework-agnostic](https://developers.arcgis.com/calcite-design-system/get-started/) so the framework and setup should fit the use case desired, with the setup and support from the framework at the user's discretion.

Calcite provides this repo with some examples to get folks started and familiar with its use across a variety of frameworks. At this time there are no plans to add a NextJS example, however a case can be submitted to [Esri Support](https://www.esri.com/contact?rsource=%2Fcontact&t=5#c=us&t=5), where an enhancement could be requested, which help build cases to help prioritize enhancements requests and provide tracking progress.

[Learn more about submitting cases](https://community.esri.com/t5/my-esri-blog/why-can-t-i-submit-cases-or-how-i-became-an/ba-p/888179), including how to become an authorized caller to report an issue.

**Comment by mstuart1** [comment]
Thanks for your response Kitty.  I'll try the community forum to see if anyone can help.
