### ISSUE TITLE
React Example doesn't work unless you call setAssetPath()

### ISSUE THREAD

**Issue by jag-eagle-technology** [Esri/calcite-components-examples#84]
If you don't use the setAssetPath() function to set the location of assets, the following error will be thrown any time a component tries to retrieve an icon. Path doesn't seem to default to use the path to the assets copied by ncp as in the example. 

Unsure if this is a documentation or library issue. Setting the resourcesUrl in defineCustomElements appeared to have no effect.

```
index.js:2684 Uncaught (in promise) TypeError: Failed to construct 'URL': Invalid base URL
    at getAssetPath (index.js:2684:1)
    at fetchIcon (calcite-icon2.js:41:1)
    at CalciteIcon.loadIconPathData (calcite-icon2.js:139:1)
    at calcite-icon2.js:107:1
    at calcite-icon2.js:147:1
    at Array.forEach (<anonymous>)
    at IntersectionObserver.intersectionObserver.Object.rootMargin (calcite-icon2.js:143:1)
```

**Comment by benelan** [comment]
Thanks for reporting this issue! I just fixed the example. I recently switched the sample to use the [`custom-elements` build](https://stenciljs.com/docs/custom-elements) which behaves a bit differently. This is the recommended build for frontend frameworks as stencil mentions in their doc. Let me know if you have any questions.

**Comment by benelan** [comment]
To follow up on the `defineCustomElements` comment, in this build you need to [import the components individually](https://github.com/Esri/calcite-components-examples/blob/master/react/src/App.js#L2-L4) when you use them, and they are automatically defined on the window. We recommend using this build, but if you need the [`dist` build](https://stenciljs.com/docs/distribution) which has `defineCustomElements`, we still provide that as well. For reference, we [use that build](https://github.com/Esri/calcite-components-examples/blob/master/ember/app/initializers/calcite-components.js#L1-L5) in the ember example.

**Comment by jag-eagle-technology** [comment]
Ah I see - I might just be looking in the wrong place for docs but should the details on the NPM page be updated? https://www.npmjs.com/package/@esri/calcite-components-react

**Comment by benelan** [comment]
Thanks for pointing that out! I'll update the doc there to provide information about using both of the builds. You can still use the build documented there if necessary. Going back in the version control, [here]((https://github.com/Esri/calcite-components-examples/blob/37d03f88958d10065efeca4b2e06e8840fa7fb7c/react/src/index.js#L6-L16)) uses the build documented on npm and it still works. Just make sure to import from `@esri/calcite-components/dist/loader` when using `defineElements`, and import from `@esri/calcite-components/dist/components` when using the new, recommended build.

**Comment by jag-eagle-technology** [comment]
Ah thanks that's making sense now. Thanks for clarifying!

**Comment by benelan** [comment]
No problem! Also, here is the [official documentation](https://developers.arcgis.com/calcite-design-system/), which will be helpful while you develop. It has information about all of the components, an icon search, getting started instructions, a tutorial, etc.
